import type { PluginManifest } from "./types";

/**
 * 内置插件目录。
 * 把原来散落各处的 skill / tool / connector preset / project preset / expert 统一收敛到 manifest，
 * 新增能力只需新增一条 manifest，无需改业务代码。
 */

export const BUILTIN_SKILL_PLUGINS: PluginManifest[] = [
  {
    id: "summarize",
    name: "总结",
    description: "当需要总结对话或输入内容时使用。压缩信息但保留关键结论、约束、风险和后续待办。",
    version: "1.0.0",
    author: "Omni",
    kind: "skill",
    category: "内容创作",
    icon: "ScrollText",
    command: "/summarize",
    systemPrompt: "当前任务是总结。压缩信息但保留关键结论、约束、风险和后续待办，不扩写无根据内容。",
    promptPrefix: "请总结下面内容，保留关键结论、约束和待办：",
  },
  {
    id: "rewrite",
    name: "改写",
    description: "当需要改写内容、让表达更清晰自然时使用。保持原意和事实不变，优化结构、语气和可读性。",
    version: "1.0.0",
    author: "Omni",
    kind: "skill",
    category: "内容创作",
    icon: "Pencil",
    command: "/rewrite",
    systemPrompt: "当前任务是改写。保持原意和事实不变，优化结构、语气和可读性，不新增未提供的信息。",
    promptPrefix: "请改写下面内容，让表达更清晰、自然、可直接使用：",
  },
  {
    id: "translate",
    name: "翻译",
    description: "当需要翻译文本时使用。未指定目标语言时默认翻译成中文，保留术语、代码和专有名词。",
    version: "1.0.0",
    author: "Omni",
    kind: "skill",
    category: "内容创作",
    icon: "Languages",
    command: "/translate",
    systemPrompt: "当前任务是翻译。优先准确传达原意；未指定目标语言时翻译成中文；保留必要的术语、代码和专有名词。",
    promptPrefix: "请翻译下面内容；如果用户没有指定目标语言，默认翻译成中文：",
  },
  {
    id: "explain",
    name: "解释",
    description: "当需要解释概念、代码或文本时使用。先给简明结论，再说明背景、关键点、例子和常见误解。",
    version: "1.0.0",
    author: "Omni",
    kind: "skill",
    category: "知识管理",
    icon: "BookOpen",
    command: "/explain",
    systemPrompt: "当前任务是解释。先给简明结论，再说明背景、关键点、例子和常见误解；不要把解释写成泛泛教程。",
    promptPrefix: "请解释下面内容，说明背景、关键点和容易误解的地方：",
  },
  {
    id: "compare",
    name: "比较",
    description: "当需要比较多个方案、概念或文本差异时使用。围绕差异、适用场景、优缺点和推荐结论组织回答。",
    version: "1.0.0",
    author: "Omni",
    kind: "skill",
    category: "知识管理",
    icon: "GitCompare",
    command: "/compare",
    systemPrompt: "当前任务是比较。围绕差异、适用场景、优缺点和推荐结论组织回答；如果信息不足，明确比较依据有限。",
    promptPrefix: "请比较下面内容，给出差异、优缺点和推荐结论：",
  },
];

export const BUILTIN_TOOL_PLUGINS: PluginManifest[] = [
  {
    id: "new",
    name: "新对话",
    description: "当用户想开始一个全新空白对话时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "系统",
    icon: "Plus",
    command: "/new",
    promptContribution: "可调用 /new 开始一个全新空白对话，适合切换话题或清理上下文。",
  },
  {
    id: "clear",
    name: "清空消息",
    description: "当用户想清空当前对话中的消息时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "系统",
    icon: "Trash2",
    command: "/clear",
    promptContribution: "可调用 /clear 清空当前对话中的消息，但保留助手与个性化设定。",
  },
  {
    id: "settings",
    name: "打开设置",
    description: "当用户想调整偏好、模型或个性化设置时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "系统",
    icon: "Settings",
    command: "/settings",
    promptContribution: "可调用 /settings 打开设置页面，引导用户调整偏好、模型或个性化。",
  },
  {
    id: "pet",
    name: "宠物",
    description: "当用户想唤醒或收起桌面宠物时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "系统",
    icon: "PawPrint",
    command: "/pet",
    promptContribution: "可调用 /pet 唤醒或收起桌面宠物（桌宠形态），用于轻量陪伴交互。",
  },
  {
    id: "model",
    name: "切换模型",
    description: "当用户想切换当前会话使用的模型时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "系统",
    icon: "Cpu",
    command: "/model",
    promptContribution: "可调用 /model <模型 ID 或名称> 切换当前会话使用的模型。",
  },
  {
    id: "remember",
    name: "记住",
    description: "当用户想把一条长期偏好或约束保存到当前助手记忆库时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "记忆",
    icon: "Bookmark",
    command: "/remember",
    promptContribution: "可调用 /remember <内容> 把一条稳定偏好或约束写入当前助手的长期记忆库。",
  },
  {
    id: "rename",
    name: "重命名对话",
    description: "当用户想重命名当前对话时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "系统",
    icon: "Type",
    command: "/rename",
    promptContribution: "可调用 /rename <标题> 重命名当前对话，便于后续检索。",
  },
  {
    id: "pin",
    name: "置顶对话",
    description: "当用户想置顶或取消置顶当前对话时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "系统",
    icon: "Pin",
    command: "/pin",
    promptContribution: "可调用 /pin 置顶或取消置顶当前对话。",
  },
  {
    id: "search_sessions",
    name: "搜索会话",
    description: "当用户想按标题或内容搜索本地历史会话时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "知识管理",
    icon: "Search",
    command: "/search_sessions",
    promptContribution: "可调用 /search_sessions <关键词> 按标题或内容检索本地历史会话。",
  },
  {
    id: "read_session",
    name: "读取会话",
    description: "当用户想查看指定会话的上下文内容时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "知识管理",
    icon: "MessageSquare",
    command: "/read_session",
    promptContribution: "可调用 /read_session <会话 ID> 读取指定历史会话的完整上下文。",
  },
  {
    id: "list_files",
    name: "列出文件",
    description: "当用户想浏览当前工作区的文件和目录结构时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "开发编程",
    icon: "FolderTree",
    command: "/list_files",
    promptContribution: "可调用 /list_files [路径] 浏览工作区文件和目录结构，用于定位资料。",
  },
  {
    id: "read_file",
    name: "读取文件",
    description: "当用户想读取文件正文用于分析或问答时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "开发编程",
    icon: "FileText",
    command: "/read_file",
    promptContribution: "可调用 /read_file <路径> 读取文件正文，用于分析或问答。",
  },
  {
    id: "search_files",
    name: "搜索文件",
    description: "当用户想按关键字搜索工作区内容时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "开发编程",
    icon: "FileSearch",
    command: "/search_files",
    promptContribution: "可调用 /search_files <关键词> 在工作区范围内按关键字检索文件内容。",
  },
  {
    id: "analyze_files",
    name: "分析文件",
    description: "当用户想结合搜索和读取完成文件分析任务时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "开发编程",
    icon: "FileBarChart",
    command: "/analyze_files",
    promptContribution: "可调用 /analyze_files <任务> 结合搜索与读取完成文件级分析任务。",
  },
  {
    id: "read_persona",
    name: "读取个性化档案",
    description: "当用户想读取本地个性化 md 文件的内容（user_name / assistant_name / persona_description / custom_instruction / long_term_memory / agents_md / style）时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "记忆",
    icon: "UserCircle",
    command: "/read_persona",
    promptContribution:
      "可调用 /read_persona <字段> 读取本地个性化档案（称呼、名字、人设、自定义指令、长期记忆、AGENTS.md、风格），用于贴合用户偏好。",
  },
  {
    id: "update_persona",
    name: "更新个性化档案",
    description: "当用户想把稳定的偏好、称呼或人设写入对应个性化 md 文件时调用。",
    version: "1.0.0",
    author: "Omni",
    kind: "tool",
    category: "记忆",
    icon: "UserCog",
    command: "/update_persona",
    promptContribution:
      "可调用 /update_persona <字段> <内容> 把稳定的偏好、称呼或人设写入对应个性化 md 文件（含 AGENTS.md），用法：/update_persona <字段> <内容>。",
  },
];

export const BUILTIN_CONNECTOR_PLUGINS: PluginManifest[] = [
  {
    id: "openai",
    name: "OpenAI",
    description: "连接 OpenAI 官方 API。",
    version: "1.0.0",
    author: "Omni",
    kind: "connector",
    category: "模型",
    icon: "Cloud",
    provider: "openai",
    baseUrl: "https://api.openai.com/v1",
    configFields: [
      { id: "apiKey", label: "API Key", type: "password", required: true, placeholder: "sk-..." },
      { id: "baseUrl", label: "Base URL（可选）", type: "string", placeholder: "https://api.openai.com/v1" },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    description: "连接 DeepSeek 官方 API。",
    version: "1.0.0",
    author: "Omni",
    kind: "connector",
    category: "模型",
    icon: "Zap",
    provider: "deepseek",
    baseUrl: "https://api.deepseek.com/v1",
    configFields: [{ id: "apiKey", label: "API Key", type: "password", required: true, placeholder: "..." }],
  },
  {
    id: "claude",
    name: "Claude",
    description: "连接 Anthropic Claude API。",
    version: "1.0.0",
    author: "Omni",
    kind: "connector",
    category: "模型",
    icon: "MessagesSquare",
    provider: "claude",
    baseUrl: "https://api.anthropic.com/v1",
    configFields: [{ id: "apiKey", label: "API Key", type: "password", required: true, placeholder: "sk-ant-..." }],
  },
  {
    id: "gemini",
    name: "Gemini",
    description: "连接 Google Gemini API。",
    version: "1.0.0",
    author: "Omni",
    kind: "connector",
    category: "模型",
    icon: "Sparkles",
    provider: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    configFields: [{ id: "apiKey", label: "API Key", type: "password", required: true, placeholder: "..." }],
  },
  {
    id: "ollama",
    name: "Ollama",
    description: "连接本地 Ollama 服务。",
    version: "1.0.0",
    author: "Omni",
    kind: "connector",
    category: "模型",
    icon: "Server",
    provider: "ollama",
    baseUrl: "http://localhost:11434/v1",
    configFields: [{ id: "baseUrl", label: "服务地址", type: "string", required: true, placeholder: "http://localhost:11434/v1" }],
  },
];

export const BUILTIN_EXPERT_PLUGINS: PluginManifest[] = [
  {
    id: "dev-expert",
    name: "编程专家",
    description: "当任务涉及代码审查、架构设计、Bug 诊断、重构或技术选型时使用。",
    version: "1.0.0",
    author: "Omni",
    kind: "expert",
    category: "开发编程",
    icon: "Code2",
    tags: ["coding", "review", "architecture"],
    templatePrompt:
      "你是一名资深工程师。优先给出可运行的代码或清晰的排查步骤，不做空泛描述。需要时主动请求查看相关文件。",
    defaultToolIds: ["list_files", "read_file", "search_files", "analyze_files"],
    defaultSkillIds: ["explain", "compare"],
  },
  {
    id: "writer-expert",
    name: "写作专家",
    description: "当任务涉及文案润色、文档撰写、PR 描述或提示词优化时使用。",
    version: "1.0.0",
    author: "Omni",
    kind: "expert",
    category: "内容创作",
    icon: "PenTool",
    tags: ["writing", "polish"],
    templatePrompt:
      "你是一名专业文字编辑。保持原意不变，优化结构、语气和可读性，给出可直接使用的版本，并说明修改理由。",
    defaultToolIds: ["read_file"],
    defaultSkillIds: ["rewrite", "summarize"],
  },
  {
    id: "pm-expert",
    name: "产品方案专家",
    description: "当任务涉及需求拆解、方案梳理、执行规划或决策比较时使用。",
    version: "1.0.0",
    author: "Omni",
    kind: "expert",
    category: "商业运营",
    icon: "LayoutTemplate",
    tags: ["planning", "decision"],
    templatePrompt:
      "你是一名产品经理。先把需求拆成目标、约束、可选方案和下一步行动，再给出推荐并说明依据。",
    defaultToolIds: ["search_sessions", "read_session"],
    defaultSkillIds: ["compare", "summarize"],
  },
];

export const BUILTIN_TEMPLATE_PLUGINS: PluginManifest[] = [
  {
    id: "solution-planner",
    name: "方案梳理助手",
    description: "帮你拆解需求、整理方案并规划执行步骤。",
    version: "1.0.0",
    author: "Omni",
    kind: "template",
    category: "商业运营",
    icon: "Map",
    templatePrompt: "请帮我梳理当前问题的背景、目标、约束、可选方案和下一步执行计划。",
    defaultToolIds: ["search_sessions", "read_session"],
    defaultSkillIds: ["summarize", "compare"],
  },
  {
    id: "code-debugger",
    name: "代码排查助手",
    description: "适合定位报错、梳理链路和修复方向。",
    version: "1.0.0",
    author: "Omni",
    kind: "template",
    category: "开发编程",
    icon: "Bug",
    templatePrompt:
      "请帮我定位问题根因。优先查看报错堆栈和相关代码，给出最小复现步骤和修复方案。",
    defaultToolIds: ["list_files", "read_file", "search_files", "analyze_files"],
    defaultSkillIds: ["explain"],
  },
  {
    id: "copy-polisher",
    name: "文案润色助手",
    description: "用于改写说明文档、PR 描述和提示词。",
    version: "1.0.0",
    author: "Omni",
    kind: "template",
    category: "内容创作",
    icon: "Highlighter",
    templatePrompt: "请润色下面这段文字，使其表达清晰、自然、可直接使用，并保持原意不变。",
    defaultToolIds: ["read_file"],
    defaultSkillIds: ["rewrite"],
  },
  {
    id: "command-helper",
    name: "效率命令助手",
    description: "快速生成常用命令、脚本和操作建议。",
    version: "1.0.0",
    author: "Omni",
    kind: "template",
    category: "开发编程",
    icon: "Terminal",
    templatePrompt: "请根据我的需求生成对应的命令或脚本，并说明每个关键参数的含义和风险。",
    defaultToolIds: ["search_sessions"],
    defaultSkillIds: ["explain"],
  },
];

export const BUILTIN_PLUGINS: PluginManifest[] = [
  ...BUILTIN_SKILL_PLUGINS,
  ...BUILTIN_TOOL_PLUGINS,
  ...BUILTIN_CONNECTOR_PLUGINS,
  ...BUILTIN_EXPERT_PLUGINS,
  ...BUILTIN_TEMPLATE_PLUGINS,
];

/** SkillHub 风格的分类，用于插件市场筛选与统计。 */
export const PLUGIN_CATEGORIES = [
  "全部",
  "开发编程",
  "内容创作",
  "数据分析",
  "知识管理",
  "商业运营",
  "设计多媒体",
  "模型",
  "系统",
  "记忆",
];
